/**
 * Export Service — PDF generation and Calendar integration.
 * Uses built-in Expo modules (free, no API key).
 */

import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import type { GeneratedItinerary, DayItinerary } from './aiService';

// ─── PDF Export ───────────────────────────────────────────────────────────────

function generateItineraryHtml(itinerary: GeneratedItinerary): string {
  const daysHtml = itinerary.itinerary
    .map(
      (day: DayItinerary) => `
      <div style="margin-bottom: 24px; page-break-inside: avoid;">
        <div style="background: #6366F1; color: #fff; padding: 10px 16px; border-radius: 8px; margin-bottom: 12px;">
          <strong>Day ${day.day}</strong> — ${day.theme}
        </div>
        ${day.activities
          .map(
            (act) => `
          <div style="margin-left: 16px; margin-bottom: 12px; border-left: 3px solid ${
            act.time === 'Morning' ? '#F59E0B' : act.time === 'Afternoon' ? '#6366F1' : '#8B5CF6'
          }; padding-left: 12px;">
            <div style="color: ${
              act.time === 'Morning' ? '#F59E0B' : act.time === 'Afternoon' ? '#6366F1' : '#8B5CF6'
            }; font-size: 12px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.5px;">
              ${act.time} · ${act.estimatedCost}
            </div>
            <div style="font-size: 16px; font-weight: bold; margin: 4px 0 2px;">${act.activity}</div>
            <div style="color: #6B7280; font-size: 13px;">📍 ${act.location}</div>
            <div style="color: #4B5563; font-size: 13px; margin-top: 4px;">${act.description}</div>
          </div>
        `
          )
          .join('')}
      </div>
    `
    )
    .join('');

  const tipsHtml =
    itinerary.travelTips?.length > 0
      ? `
      <h2 style="color: #6366F1; margin-top: 24px;">💡 Travel Tips</h2>
      <ul style="color: #374151;">
        ${itinerary.travelTips.map((tip: string) => `<li style="margin-bottom: 6px;">${tip}</li>`).join('')}
      </ul>
    `
      : '';

  const packingHtml =
    itinerary.packingTips?.length > 0
      ? `
      <h2 style="color: #6366F1; margin-top: 24px;">🎒 Packing Tips</h2>
      <ul style="color: #374151;">
        ${itinerary.packingTips.map((tip: string) => `<li style="margin-bottom: 6px;">${tip}</li>`).join('')}
      </ul>
    `
      : '';

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8" />
      <style>
        body { font-family: -apple-system, 'Helvetica Neue', Arial, sans-serif; padding: 32px; color: #1F2937; max-width: 700px; margin: auto; }
        h1 { color: #6366F1; margin-bottom: 4px; }
        .meta { color: #6B7280; font-size: 14px; margin-bottom: 24px; }
        .summary { background: #F5F7FF; padding: 16px; border-radius: 12px; border: 1px solid #E5E7EB; margin-bottom: 24px; line-height: 1.6; }
        .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #E5E7EB; color: #9CA3AF; font-size: 12px; text-align: center; }
      </style>
    </head>
    <body>
      <h1>${itinerary.tripTitle}</h1>
      <div class="meta">
        📍 ${itinerary.destination} · 🕐 ${itinerary.duration} days · 💰 ${itinerary.estimatedTotalCost}
      </div>
      <div class="summary">${itinerary.summary}</div>
      ${daysHtml}
      ${tipsHtml}
      ${packingHtml}
      <div class="footer">
        Generated by SwiftRoute AI Travel Planner · ${new Date().toLocaleDateString()}
      </div>
    </body>
    </html>
  `;
}

export async function exportToPdf(itinerary: GeneratedItinerary): Promise<void> {
  const html = generateItineraryHtml(itinerary);

  const { uri } = await Print.printToFileAsync({
    html,
    base64: false,
  });

  const isAvailable = await Sharing.isAvailableAsync();
  if (isAvailable) {
    await Sharing.shareAsync(uri, {
      UTI: '.pdf',
      mimeType: 'application/pdf',
      dialogTitle: `${itinerary.tripTitle} Itinerary`,
    });
  }
}

// ─── Share as text ────────────────────────────────────────────────────────────

export function generateShareText(itinerary: GeneratedItinerary): string {
  let text = `✈️ ${itinerary.tripTitle}\n`;
  text += `📍 ${itinerary.destination} · ${itinerary.duration} days\n`;
  text += `💰 ${itinerary.estimatedTotalCost}\n\n`;
  text += `${itinerary.summary}\n\n`;

  itinerary.itinerary.forEach((day: DayItinerary) => {
    text += `📅 Day ${day.day}: ${day.theme}\n`;
    day.activities.forEach((act) => {
      text += `  ${act.time}: ${act.activity} (${act.location}) - ${act.estimatedCost}\n`;
    });
    text += '\n';
  });

  text += 'Planned with SwiftRoute AI ✨';
  return text;
}
